// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1102:Make class static.", Justification = "Application entry point", Scope = "type", Target = "~T:Nortridge.BorrowerPortal.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "Application entry point", Scope = "type", Target = "~T:Nortridge.BorrowerPortal.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Startup (.net core convention)", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "GlobalSuppressions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "function name", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Prelude.keyValuePair``2(``0,``1)~System.Collections.Generic.KeyValuePair{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "Array uses in a form", Scope = "member", Target = "~P:Nortridge.BorrowerPortal.Pages.Nicknames.IndexModel.Loans")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "asp .net convention", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Pages.Account.IndexModel.OnPostAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Exception message", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Core.Auth.AuthorizationHeaderHandler.AccessTokenImportXml~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "Deserialization object", Scope = "member", Target = "~P:Nortridge.BorrowerPortal.NlsWebApiExceptionResponse.Errors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "Trusted", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Pages.SubmitPayment.SubmitPaymentWebpay.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "Trusted", Scope = "member", Target = "~P:Nortridge.BorrowerPortal.Pages.SubmitPayment.SubmitPaymentWebpay.Url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "function name", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Prelude.lazy``1(System.Func{``0})~System.Lazy{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "function name", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Prelude.commonError``1(``0)~Nortridge.BorrowerPortal.Core.Infrastructure.CommonError{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "function name", Scope = "member", Target = "~M:Nortridge.BorrowerPortal.Prelude.commonError``1(``0,System.String)~Nortridge.BorrowerPortal.Core.Infrastructure.CommonError{``0}")]
